drop database HERRAMIENTAVRT;
CREATE DATABASE IF NOT EXISTS HERRAMIENTAVRT;
USE HERRAMIENTAVRT;

CREATE TABLE reportes
(
  id_reporte INT NOT NULL AUTO_INCREMENT,
  fecha_reporte DATETIME NOT NULL,
  folder VARCHAR(500) NOT NULL,
  info_importante VARCHAR(500) NOT NULL,
  PRIMARY KEY(id_reporte)
);
